# XDG Desktop Portal Preferred Configuration
# Copy this file to ~/.config/xdg-desktop-portal/portals.conf

[preferred]
default=hyprland;gtk
org.freedesktop.impl.portal.FileChooser=prism
org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.ScreenCast=hyprland

